// Powered by OnSpace.AI
import { Track } from '@/types/music';

export const MOCK_TRACKS: Track[] = [
  {
    id: '1',
    title: 'Midnight Drive',
    artist: 'Luna Eclipse',
    album: 'Neon Nights',
    duration: 214,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 1,
    filename: 'midnight_drive.mp3',
    size: 8500000,
  },
  {
    id: '2',
    title: 'Cosmic Waves',
    artist: 'Solar Wind',
    album: 'Beyond Stars',
    duration: 183,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 2,
    filename: 'cosmic_waves.mp3',
    size: 7200000,
  },
  {
    id: '3',
    title: 'Electric Soul',
    artist: 'Neon Drift',
    album: 'Voltage',
    duration: 247,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 3,
    filename: 'electric_soul.mp3',
    size: 9800000,
  },
  {
    id: '4',
    title: 'Deep Blue',
    artist: 'Ocean Pulse',
    album: 'Tides',
    duration: 198,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 4,
    filename: 'deep_blue.mp3',
    size: 7900000,
  },
  {
    id: '5',
    title: 'Fire & Rain',
    artist: 'Storm Circuit',
    album: 'Elements',
    duration: 225,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 5,
    filename: 'fire_rain.mp3',
    size: 8900000,
  },
  {
    id: '6',
    title: 'Golden Hour',
    artist: 'Aurora Bloom',
    album: 'Sunrise',
    duration: 192,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 6,
    filename: 'golden_hour.mp3',
    size: 7600000,
  },
  {
    id: '7',
    title: 'Shadow Walk',
    artist: 'Phantom Lanes',
    album: 'Dark Roads',
    duration: 261,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 7,
    filename: 'shadow_walk.mp3',
    size: 10400000,
  },
  {
    id: '8',
    title: 'Pulse of the City',
    artist: 'Urban Freq',
    album: 'Metropolis',
    duration: 209,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 8,
    filename: 'pulse_city.mp3',
    size: 8300000,
  },
  {
    id: '9',
    title: 'Velvet Sky',
    artist: 'Nightfall',
    album: 'Dusk',
    duration: 178,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 9,
    filename: 'velvet_sky.mp3',
    size: 7100000,
  },
  {
    id: '10',
    title: 'Neon Paradise',
    artist: 'Retro Wave',
    album: '80s Vibes',
    duration: 234,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 10,
    filename: 'neon_paradise.mp3',
    size: 9300000,
  },
  {
    id: '11',
    title: 'Crystal Clear',
    artist: 'Glass Echo',
    album: 'Transparency',
    duration: 201,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 0.5,
    filename: 'crystal_clear.mp3',
    size: 8000000,
  },
  {
    id: '12',
    title: 'Horizon Line',
    artist: 'Endless Road',
    album: 'Journey',
    duration: 258,
    uri: '',
    artwork: null,
    dateAdded: Date.now() - 86400000 * 0.2,
    filename: 'horizon_line.mp3',
    size: 10300000,
  },
];

export const ACCENT_COLORS = [
  '#FC3C44', '#5E5CE6', '#30D158', '#FFD60A',
  '#BF5AF2', '#FF9F0A', '#64D2FF', '#FF6B70',
];
